### ISSUE TITLE
Implement cbc.ca

### ISSUE THREAD

**Issue by jpmckinney** [opennorth/govkit-ca#1]
e.g. https://votecompass.cbc.ca/home/find-riding-district/a1a-1a1

**Comment by ianknauer** [comment]
Any idea if this lookup is supposed to be sticking around after the election?

**Comment by jpmckinney** [comment]
The 2011 lookup stuck around for 2-3 years, but no idea what the case will be this time.

**Comment by jpmckinney** [comment]
Also http://ridinglookup.cloudapp.net/?pc=a1a1a1

**Comment by jpmckinney** [comment]
No longer available.
