### ISSUE TITLE
Profide full example script

### ISSUE THREAD

**Issue by mgifford** [opennorth/govkit-ca#2]
I wrote up a quick example script. starting with 

```
#!/usr/bin/env ruby
require 'govkit-ca'
```

But I'm not a ruby guy.  Had to dig around before knowing where to start.

**Comment by jpmckinney** [comment]
Doesn't https://github.com/opennorth/govkit-ca#represent-api have enough examples?

**Comment by mgifford** [comment]
I think that assumes you know the API. I just want a simple example script that will return a riding name & MP given a postal code.

I think this is as simple as it gets 

```
#!/usr/bin/env ruby

require 'govkit-ca'

# Register the sources to use.
GovKit::CA::PostalCode::StrategySet.register(GovKit::CA::PostalCode::Strategy::ElectionsCa)

# Initiate the client
client = GovKit::CA::Represent.new

# Print the EDID based on postal code
print GovKit::CA::PostalCode.find_electoral_districts_by_postal_code('A1A1A1') # [10007]

# Find the riding name based on EDID

# Find the MP based on the EDID
```

But I'm missing the find_riding_name_by_postal_code or find_riding_name_by_electoral_districts function which I assume exists. And for that matter the similar one for MP name.

**Comment by jpmckinney** [comment]
This gem isn't being actively developed. I think you'll find it much easier to use the Represent API directly, which can do all these things: http://represent.opennorth.ca/api/

If you want to use the code from this gem that uses elections.ca and other websites to look up federal ridings based on postal code, you can still get the riding name from the Represent API using the EDID:

http://represent.opennorth.ca/boundaries/federal-electoral-districts/10001/

And the representative's name:

http://represent.opennorth.ca/boundaries/federal-electoral-districts/10001/representatives/

**Comment by jpmckinney** [comment]
Also, those elections.ca strategies may be broken and aren't maintained (they require regular changes whenever sources change the layout/operation of their websites).

**Comment by mgifford** [comment]
Thanks James.
