### ISSUE TITLE
EDID vs Riding

### ISSUE THREAD

**Issue by mgifford** [opennorth/govkit-ca#3]
Can I not just get a Riding name rather than an EDID?  Even if it has to go through 2 queries, can you show me how to query the API for the Riding name?  

Seems kinda crazy that there isn't just a CSV file of the Ridning name & EDID posted here http://www.elections.ca/content.aspx?section=res&dir=cir/list&document=index338&lang=e

**Comment by jpmckinney** [comment]
Can you share your code? I'm not sure what you're trying to do.

**Comment by mgifford** [comment]
Thanks James..  I did that in the other issue.  I do think that it is common though to have a list of postal codes and want to know the riding name & MP vs the EDID.

**Comment by jpmckinney** [comment]
Answered in #2.
