### ISSUE TITLE
2019 Canadian Federal election

### ISSUE THREAD

**Issue by KelseyDH** [opennorth/govkit-ca#4]
Nice API, will this be updated with candidate data before the 2019 Canadian Federal election in October?  Also wondering if this feed will tap into live election results that night or if I'll have to look somewhere else for that.

**Comment by jpmckinney** [comment]
Yes, please email represent@opennorth.ca for questions about the API.

The API doesn't distribute election results – Elections Canada (and maybe the major media companies) have this information.
